[package]
name = "bomberust-server"
version = "0.1.0"
authors = ["Sébastien Blin <sebastien.blin@enconn.fr>"]
edition = "2018"

[dependencies]
rand="0.7"
tokio = { version = "0.1.6" }
clap = "2"
tokio-rustls="0.10"